---
- name: download kerl
  get_url: url={{erlang_kerl_url}} dest={{erlang_kerl_bin}} mode=0777
  sudo: true

- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400
  sudo: true

- name: install dependencies from apt
  apt: pkg={{item}} state=present
  sudo: true
  with_items:
  - curl
  - libssl-dev
  - libncurses5-dev
  - build-essential

- name: ensure ~/.kerlrc
  template: src=kerlrc dest={{ansible_env['HOME']}}/.kerlrc owner={{ansible_env['USER']}} mode=0744

- name: kerl update release
  command: "{{erlang_kerl_bin}} update releases creates={{ansible_env['HOME']}}/.kerl/otp_releases"

- name: build erlang
  command: "{{erlang_kerl_bin}} build {{erlang_version}} default creates={{erlang_kerl_build_dir}}/default"

- name: kerl install default erlang
  command: sudo {{erlang_kerl_bin}} install default {{erlang_install_to}}/default creates={{erlang_install_to}}/default

- name: activate erlang for users
  lineinfile: line='source {{erlang_install_to}}/default/activate' 
              dest=/etc/bash.bashrc 
              regexp='{{erlang_install_to}}/default/activate'
              state=present
  sudo: true
